---
namespace: sulzmann-energy
name: gitlab
version: 1.0.2
readme: README.md
authors:
  - Marvin Vogt <git@srv6d.space>
description: Deploy and manage GitLab CE/EE and GitLab runners.
license:
  - GPL-3.0-only
tags:
  - gitlab
  - runner
  - git
  - ci
  - devops
  - automation
  - system
  - application
  - cloud
  - infrastructure
  - tools
dependencies:
  ansible.utils: ">=2.0.1"
repository: https://github.com/srv6d/ansible_collection_gitlab
issues: https://github.com/srv6d/ansible_collection_gitlab/issues
build_ignore:
  - .github
  - .ansible-lint
  - .yamllint
  - roles/gitlab/molecule
  - roles/runner/molecule
